name: verify

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    container:
      image: devkitpro/devkitarm

    steps:
    - name: setup
      run: apt update && apt install -y build-essential cmake g++-multilib

    - name: clone
      uses: actions/checkout@v4
      with:
        submodules: recursive
      
    - name: build
      run: make

    - name: verify
      run: make verify