name: verify

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    container:
      image: pablomk7/libctrpf:0.8.0

    steps:
    - name: clone
      uses: actions/checkout@v4
      with:
        submodules: recursive
      
    - name: build
      run: make

    - name: verify
      run: make verify